### ISSUE TITLE
`tuple` type is not subscriptable

### ISSUE THREAD

**Issue by kallewesterling** [dennisbakhuis/pigeonXT#11]
Import error encountered due to `typing` library's `Tuple` not used but `tuple`:

```py
TypeError: 'type' object is not subscriptable
```

This is the full error:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/7298727/235673426-d9929bd2-cf95-4d40-a4f9-76089af98283.png">

**Comment by adnankarol** [comment]
Hello
Is this issue fixed? I am also facing the same issue


Best
Adnan

**Comment by kallewesterling** [comment]
I don't think so, @adnankarol. It seems like @dennisbakhuis hasn't looked at the PR (see https://github.com/dennisbakhuis/pigeonXT/pull/12) yet.
